FROM continuumio/miniconda3:latest

COPY . /admitad/
WORKDIR /admitad
RUN conda env create -f env.yml

EXPOSE 5000

ENTRYPOINT /opt/conda/envs/admitad/bin/gunicorn \
            -w $GUNICORN_WORKERS \
            --log-file=- \
            --worker-tmp-dir /dev/shm \
            -b 0.0.0.0:5000 \
            wsgi:app